[package]
name = "proc"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
path = "src/macros.rs"

[dependencies]
helpers = { path = "../helpers" }
ignore = "0.4.23"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.104"
